// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace CoreApp.EntityFramework.Models
{
    public partial class CoreMenu
    {
        public Guid Id { get; set; }
        public Guid? ModuleId { get; set; }
        public Guid? ViewId { get; set; }
        public string Name { get; set; }
        public string TitleDict { get; set; }
        public string Href { get; set; }
        public string Icon { get; set; }
        public int Position { get; set; }
        public Guid? ParentId { get; set; }
        public bool IsActived { get; set; }
        public DateTime? CreatedDate { get; set; }
    }
}