// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace CoreApp.EntityFramework.Models
{
    public partial class CoreViewSearchCondition
    {
        public Guid Id { get; set; }
        public Guid ColumnId { get; set; }
        public string Condition { get; set; }
        public string Operator { get; set; }
        public Guid ViewId { get; set; }
        public string Value { get; set; }
        public Guid? CreatedBy { get; set; }
        public DateTime? CreatedDate { get; set; }
        public Guid? UpdatedBy { get; set; }
        public DateTime? UpdatedDate { get; set; }
    }
}