// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace CoreApp.EntityFramework.Models
{
    public partial class CoreConfig
    {
        public Guid Id { get; set; }
        public Guid GroupId { get; set; }
        public string Name { get; set; }
        public string Value { get; set; }
        public bool IsNeedEncrypt { get; set; }
        public string DataType { get; set; }
        public string InputType { get; set; }
        public string Label { get; set; }
        public int Sort { get; set; }

        public virtual CoreConfigGroup Group { get; set; }
    }
}