// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace CoreApp.EntityFramework.Models
{
    public partial class CoreViewColumn
    {
        public Guid Id { get; set; }
        public Guid ColumnId { get; set; }
        public Guid ViewId { get; set; }
        public int Position { get; set; }
        public bool Visible { get; set; }
        public bool IsActived { get; set; }
        public string Width { get; set; }

        public virtual CoreColumn Column { get; set; }
        public virtual CoreView View { get; set; }
    }
}