// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace CoreApp.EntityFramework.Models
{
    public partial class CoreViewSpecialCondition
    {
        public Guid Id { get; set; }
        public Guid RoleId { get; set; }
        public string ViewIds { get; set; }
        public string Condition { get; set; }
        public string Column { get; set; }
        public string Operator { get; set; }
        public string Value { get; set; }
    }
}