// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace CoreApp.EntityFramework.Models
{
    public partial class CoreRole
    {
        public CoreRole()
        {
            CoreRoleModulePermissions = new HashSet<CoreRoleModulePermission>();
            CoreUserRoles = new HashSet<CoreUserRole>();
        }

        public Guid Id { get; set; }
        public string Code { get; set; }
        public string Name { get; set; }
        public bool IsActived { get; set; }
        public bool IsAdmin { get; set; }
        public Guid? CreatedBy { get; set; }
        public DateTime? CreatedDate { get; set; }
        public Guid? UpdatedBy { get; set; }
        public DateTime? UpdatedDate { get; set; }
        public bool IsSuperAdmin { get; set; }

        public virtual ICollection<CoreRoleModulePermission> CoreRoleModulePermissions { get; set; }
        public virtual ICollection<CoreUserRole> CoreUserRoles { get; set; }
    }
}