// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace CoreApp.EntityFramework.Models
{
    public partial class CoreColumn
    {
        public CoreColumn()
        {
            CoreViewColumns = new HashSet<CoreViewColumn>();
        }

        public Guid Id { get; set; }
        public string SqlName { get; set; }
        public string NameDict { get; set; }
        public string Name { get; set; }
        public Guid TableId { get; set; }
        public string TableAlias { get; set; }
        public Guid DataTypeId { get; set; }
        public bool Searchable { get; set; }
        public bool Sortable { get; set; }
        public bool IsPrimaryKey { get; set; }
        public bool IsForeignKey { get; set; }
        public string SqlScript { get; set; }
        public Guid? EnumId { get; set; }

        public virtual CoreDataType DataType { get; set; }
        public virtual CoreTable Table { get; set; }
        public virtual ICollection<CoreViewColumn> CoreViewColumns { get; set; }
    }
}