// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using CoreApp.EntityFramework.Extension;
using OfficeOpenXml.FormulaParsing.Excel.Functions.RefAndLookup;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace CoreApp.EntityFramework.Models
{
    public partial class CoreUser
    {
        public CoreUser()
        {
            CoreCredentials = new HashSet<CoreCredential>();
            CoreUserRoles = new HashSet<CoreUserRole>();
        }
        [Key]
        public Guid Id { get; set; }
        public string Name { get; set; }
        public string Email { get; set; }
        public string Phone { get; set; }
        public Guid? CreatedBy { get; set; }
        public DateTime? CreatedDate { get; set; }
        public Guid? UpdatedBy { get; set; }
        public DateTime? UpdatedDate { get; set; }

        [MaxLength(500)]
        public string Address { get; set; }
        [Required]
        public bool Gender  { get; set; }

        public virtual ICollection<CoreCredential> CoreCredentials { get; set; }
        public virtual ICollection<CoreUserRole> CoreUserRoles { get; set; }
    }
}