// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace CoreApp.EntityFramework.Models
{
    public partial class CoreTable
    {
        public CoreTable()
        {
            CoreColumns = new HashSet<CoreColumn>();
        }

        public Guid Id { get; set; }
        public string SqlName { get; set; }
        public string Name { get; set; }
        public string Alias { get; set; }
        public Guid ModuleId { get; set; }
        public DateTime? CreatedDate { get; set; }

        public virtual CoreModule Module { get; set; }
        public virtual ICollection<CoreColumn> CoreColumns { get; set; }
    }
}