// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace CoreApp.EntityFramework.Models
{
    public partial class CoreEnumValue
    {
        public Guid Id { get; set; }
        public string Code { get; set; }
        public string Slug { get; set; }
        public Guid EnumId { get; set; }
        public string Name { get; set; }
        public string Image { get; set; }

        public virtual CoreEnum Enum { get; set; }
    }
}