// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace CoreApp.EntityFramework.Models
{
    public partial class CoreCredential
    {
        public Guid Id { get; set; }
        public Guid UserId { get; set; }
        public Guid CredentialTypeId { get; set; }
        public string Identifier { get; set; }
        public string Secret { get; set; }

        public virtual CoreCredentialType CredentialType { get; set; }
        public virtual CoreUser User { get; set; }
    }
}