// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace CoreApp.EntityFramework.Models
{
    public partial class CoreRoleModulePermission
    {
        public Guid RoleId { get; set; }
        public Guid ModuleId { get; set; }
        public Guid PermissionId { get; set; }


        public virtual CoreModule Module { get; set; }
        public virtual CorePermission Permission { get; set; }
        public virtual CoreRole Role { get; set; }

    }
}