// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace CoreApp.EntityFramework.Models
{
    public partial class CoreConfigGroup
    {
        public CoreConfigGroup()
        {
            CoreConfigs = new HashSet<CoreConfig>();
        }

        public Guid Id { get; set; }
        public string Name { get; set; }
        public string Label { get; set; }
        public int? Sort { get; set; }

        public virtual ICollection<CoreConfig> CoreConfigs { get; set; }
    }
}