// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace CoreApp.EntityFramework.Models
{
    public partial class CoreDataType
    {
        public CoreDataType()
        {
            CoreColumns = new HashSet<CoreColumn>();
        }

        public Guid Id { get; set; }
        public string Code { get; set; }
        public string Name { get; set; }

        public virtual ICollection<CoreColumn> CoreColumns { get; set; }
    }
}