// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace CoreApp.EntityFramework.Models
{
    public partial class DoWard
    {
        public Guid Id { get; set; }
        public string Name { get; set; }
        public string Type { get; set; }
        public string Location { get; set; }
        public Guid? DistrictId { get; set; }
        public string DistrictCode { get; set; }
        public string Code { get; set; }

        public virtual DoDistrict District { get; set; }
    }
}